version: '3.9'

services:
  noteit_db:
    image: mongo:4.4.4
    ports:
      - "42001:27017"
    hostname: noteit_db
    restart: unless-stopped
    container_name: noteit_db
    environment:
      MONGO_INITDB_DATABASE: noteitdb
      MONGO_INITDB_ROOT_USERNAME: noteitdb_user
      MONGO_INITDB_ROOT_PASSWORD: pa55word123
    volumes:
      - noteit_db_volume:/data/db
      - ../db/noteitdb.js:/docker-entrypoint-initdb.d/noteitdb.js:ro
    command: mongod


volumes:
  noteit_db_volume: